export const UNIDADES_EQUIPES: Record<string, string[]> = {
  "SMS CF ALICE DE JESUS REGO AP 53": ["BAIXADINHA", "JESUÍTAS", "MERCADANTE", "NOVO CONDOMÍNIO"],
  "SMS CF DEOLINDO COUTO AP 53": ["BONS AMIGOS", "DR. CONTINENTINO", "JAQUEIRA", "MARQUES DE ERVAL", "PEDRINHAS"],
  "SMS CF EDSON ABDALLA SAAD AP 53": ["CENTRO CULTURAL", "MARCOLINA", "ESPERANÇA", "PALESTINA", "PRAÇA DO MAIA", "VETERANO"],
  "SMS CF ERNANI DE PAIVA FERREIRA BRAGA AP 53": ["GUANDU E GUANDU", "GUANDU E LIBERDADE", "HORTO FLORESTAL", "JOÃO XXIII", "MIÉCIMO", "PADRE GUILHERME DECAMINADA", "SERAFIM VIEGAS", "VILLAGE ATLANTA"],
  "SMS CF HELANDE DE MELLO GONCALVES AP 53": ["JÚLIA MIGUEL", "PARQUE SÃO PAULO", "VIEIRAS"],
  "SMS CF ILZO MOTTA DE MELLO AP 53": ["MARIA APARECIDA", "ROBERTO MORENA", "TRÊS PONTES"],
  "SMS CF JAMIL HADDAD AP 53": ["AGAI", "ANDORINHAS", "AUSTIN", "COLINA", "IPEG"],
  "SMS CF JOAO BATISTA CHAGAS AP 53": ["ÁGUAS DA PRATA", "FUTURO", "NOVA ESPERANÇA", "OLINDINA", "VENDA DE VARANDA"],
  "SMS CF JOSE ANTONIO CIRAUDO AP 53": ["MANOEL JÚLIO", "COQUEIRAL (C)", "AURORA", "SÃO DOMINGOS SÁVIO", "VITOR DUMAS", "SÃO BENEDITO", "AREIA BRANCA"],
  "SMS CF LENICE MARIA MONTEIRO COELHO AP 53": ["BOA ESPERANÇA", "LOTE 14", "PARQUE DAS PEDRAS", "SAQUASSU"],
  "SMS CF LOURENCO DE MELLO AP 53": ["ALZIRA GENI", "ALZIRA MARTINHO", "BAIRRO FARIAS"],
  "SMS CF SAMUEL PENHA VALLE AP 53": ["ALTA", "TORRE", "VAGÃO"],
  "SMS CF SERGIO AROUCA AP 53": ["BOA VISTA", "BODEGÃO", "CAMPEIRO MOR", "GENERAL OLÍMPIO", "IMPÉRIO", "JARDIM ITÁ"],
  "SMS CF VALERIA GOMES ESTEVES AP 53": ["PIAI", "PEDRO LEITÃO", "BARREIRA", "EUCALIPAL", "BALNEÁRIO GLOBO"],
  "SMS CF WALDEMAR BERARDINELLI AP 53": ["AMAZONAS", "AREAL", "COQUEIRAL (W)", "ILHA DO TATU", "IPIRANGA", "MIRANTE", "TRÊS PODERES", "TRIUNFO"],
  "SMS CMS ADELINO SIMOES NOVA SEPETIBA AP 53": ["DIAMANTE", "ESMERALDA", "RUBI", "SAFIRA", "TOPÁZIO"],
  "SMS CMS ALOYSIO AMANCIO DA SILVA AP 53": ["MORRO DO AR"],
  "SMS CMS CATTAPRETA AP 53": ["ALVORADA", "CHATUBA", "CONJUNTO 61"],
  "SMS CMS CESARIO DE MELLO AP 53": ["CARVALHAU", "FELIPE CARDOSO", "MARQUES", "BLASO", "CURRAL FALSO", "TASSO", "VERIDIANA"],
  "SMS CMS CYRO DE MELLO MANGUARIBA AP 53": ["JOÃO DE BARRO", "NOVA ÍNDIA", "PARAÍSO"],
  "SMS CMS DECIO AMARAL FILHO AP 53": ["BARRO VERMELHO", "MAESTRO OLÍMPIO", "URUCÂNIA", "BAMBUZAL", "VALE DOS PALMARES"],
  "SMS CMS EMYDIO CABRAL AP 53": ["1º DE ABRIL", "DR. HÉLIO RIBEIRO", "GOUVEIA", "MONTE DAS OLIVEIRAS", "MONTE SINAI"],
  "SMS CMS FLORIPES GALDINO PEREIRA AP 53": ["SAGRADO CORAÇÃO", "NOVO HORIZONTE"],
  "SMS CMS MARIA APARECIDA DE ALMEIDA AP 53": ["CESARINHO"],
  "SMS CMS SAVIO ANTUNES ANTARES AP 53": ["CAMPO DOS BANDEIRANTES", "PONTE AMARELA", "SEMPRE VIDA"]
};

export const MICROAREAS = ["1", "2", "3", "4", "5", "6", "7"];
